[package]
name = "hashstack_contracts"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.23.0" } 0.23.0
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.23.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[lib]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[tool.fmt]
sort-module-level-items = true